version: "3"

services:
  tooling_app:
    build: .
    container_name: tooling_app
    ports:
      - ${APP_PORT}:80
    volumes:
      - tooling_app:/var/www/html
    links:
      - tooling_db
    depends_on:
      - tooling_db
  tooling_db:
    image: mysql:5.7
    hostname: ${MYSQL_HOSTNAME}
    container_name: tooling_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_app:
  db:
    

    